// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  示例命令：P0 用于验证 specta 契约链路（生成 → 引用 → CI 一致性检查） */
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	/**  启动导入：选择文件夹 → 引擎后台跑（重试 = 对同一文件夹再导一次，哈希幂等） */
	importFolder: (folder: string) => typedError<number, string>(__TAURI_INVOKE("import_folder", { folder })),
	pauseImport: () => __TAURI_INVOKE<void>("pause_import"),
	resumeImport: () => __TAURI_INVOKE<void>("resume_import"),
	/**  停止当前导入（确认后）；已处理部分保留，续传 = 重新导入同一文件夹 */
	stopImport: () => __TAURI_INVOKE<void>("stop_import"),
	/**  当前任务快照（前端轮询兜底，事件丢失时恢复用） */
	importSnapshot: () => typedError<ImportProgressEvent, string>(__TAURI_INVOKE("import_snapshot")),
	/**  时间轴分页查询：按拍摄时间降序，前端按年分组展示 */
	listTimeline: (cursor: string | null, pageSize: number | null, folderId: number | null) => typedError<TimelinePage, string>(__TAURI_INVOKE("list_timeline", { cursor, pageSize, folderId })),
	/**  原图绝对路径（asset protocol 读取；scope 在导入时放行） */
	getAssetImage: (assetId: number) => typedError<string, string>(__TAURI_INVOKE("get_asset_image", { assetId })),
	/**  批量删除记录与缩略图（永不触碰原文件） */
	deleteAssets: (assetIds: number[]) => typedError<DeleteReport, string>(__TAURI_INVOKE("delete_assets", { assetIds })),
	/**  失败清单 */
	listFailedItems: () => typedError<FailedItem[], string>(__TAURI_INVOKE("list_failed_items")),
	modelStatus: () => __TAURI_INVOKE<ModelStatus>("model_status"),
	/**
	 *  下载模型资产（后台线程；进度经事件上报，完成后加载并广播就绪）。
	 *  幂等：已就绪或已有下载任务时直接返回。启动时模型缺失即自动调用（spec 0004 修订）。
	 */
	downloadModels: () => typedError<null, string>(__TAURI_INVOKE("download_models")),
	/**  混合检索（规格 0003/0005）：语义流 + 文本流 → RRF（k=60）融合，过滤前置 */
	searchAssets: (query: string, topK: number | null, filters: {
	taken_from: number | null,
	taken_to: number | null,
	kind: string | null,
	/**  搜索范围（v8 裁定：跟随侧栏所选工作区；None=全部） */
	folder_id: number | null,
} | null) => typedError<SearchPage, string>(__TAURI_INVOKE("search_assets", { query, topK, filters })),
	/**  重建全部向量索引（模型变更/量化策略变更时）；worker 轮询发现空队列后全量重嵌 */
	reindexAll: () => typedError<number, string>(__TAURI_INVOKE("reindex_all")),
	/**
	 *  重建某工作区的全部向量（所有 active 索引）；worker 轮询自动重嵌，进度经
	 *  EmbedProgressEvent 逐张可见。返回清掉的向量数。重建期间该工作区语义搜索暂缺。
	 */
	reindexFolder: (folderId: number) => typedError<number, string>(__TAURI_INVOKE("reindex_folder", { folderId })),
	/**  重新向量化指定资产（灯箱单张/网格批量共用）；worker 轮询自动重嵌。返回清掉的向量数。 */
	reindexAssets: (assetIds: number[]) => typedError<number, string>(__TAURI_INVOKE("reindex_assets", { assetIds })),
	dataInfo: () => __TAURI_INVOKE<DataInfo>("data_info"),
	/**  用系统文件管理器打开数据目录；目录丢失时重建后重试一次（规格 0006 §3.3） */
	openDataFolder: () => typedError<null, string>(__TAURI_INVOKE("open_data_folder")),
	/**  更改数据位置：校验可写与嵌套关系后写入 config.data_dir，重启生效（规格 0006 §3.2） */
	setDataLocation: (dir: string) => typedError<null, string>(__TAURI_INVOKE("set_data_location", { dir })),
	listFolders: () => typedError<FolderInfo[], string>(__TAURI_INVOKE("list_folders")),
	/**  主动重检：路径存在 → online，不存在 → missing；广播状态变化 */
	recheckFolder: (folderId: number) => typedError<FolderInfo, string>(__TAURI_INVOKE("recheck_folder", { folderId })),
	/**  重新指定丢失文件夹的新位置；该工作区资产的 storage_key 按新前缀批量改写 */
	relocateFolder: (folderId: number, newPath: string) => typedError<FolderInfo, string>(__TAURI_INVOKE("relocate_folder", { folderId, newPath })),
	/**  前端原图加载失败回调（被动检测）：该文件夹标记 offline 并广播（一次性提示由前端控制） */
	reportOriginalMissing: (assetId: number) => typedError<null, string>(__TAURI_INVOKE("report_original_missing", { assetId })),
	assetDetail: (assetId: number) => typedError<AssetDetail, string>(__TAURI_INVOKE("asset_detail", { assetId })),
	storageUsage: () => typedError<StorageUsage, string>(__TAURI_INVOKE("storage_usage")),
	/**
	 *  各工作区向量化进度快照（EmbedCard 冷启动兜底；运行中以 EmbedProgressEvent 为准）。
	 *  口径 = 第一套 active 索引（与侧栏 pending_index 徽标一致）。
	 */
	embedStatus: () => typedError<FolderEmbedStatus[], string>(__TAURI_INVOKE("embed_status")),
	inferenceInfo: () => __TAURI_INVOKE<InferenceInfo>("inference_info"),
	/**  切换推理后端：写 config.inference_ep，重启生效（spec 0008 §3.2） */
	setInferenceEp: (ep: string) => typedError<null, string>(__TAURI_INVOKE("set_inference_ep", { ep })),
	/**  下载所选变体的运行时包（后台线程；断点续传 + 校验 + 解压，spec 0008 §3.3） */
	downloadRuntime: (kind: string) => typedError<null, string>(__TAURI_INVOKE("download_runtime", { kind })),
	/**  从本地 zip 导入运行时（spec 0008 §3.4）；返回是否通过清单校验（false = 未校验来源） */
	importRuntime: (path: string) => typedError<boolean, string>(__TAURI_INVOKE("import_runtime", { path })),
	/**  从本地目录/zip 导入模型（spec 0008 §3.5）；全部匹配才落文件，否则返回明细 */
	importModels: (path: string) => typedError<ImportReport, string>(__TAURI_INVOKE("import_models", { path })),
};

/** Events */
export const events = {
	embedProgressEvent: makeEvent<EmbedProgressEvent>("embed-progress-event"),
	folderStatusChangedEvent: makeEvent<FolderStatusChangedEvent>("folder-status-changed-event"),
	importFinishedEvent: makeEvent<ImportFinishedEvent>("import-finished-event"),
	importItemFailedEvent: makeEvent<ImportItemFailedEvent>("import-item-failed-event"),
	importPausedEvent: makeEvent<ImportPausedEvent>("import-paused-event"),
	importProgressEvent: makeEvent<ImportProgressEvent>("import-progress-event"),
	importResumedEvent: makeEvent<ImportResumedEvent>("import-resumed-event"),
	modelDownloadProgressEvent: makeEvent<ModelDownloadProgressEvent>("model-download-progress-event"),
	modelReadyEvent: makeEvent<ModelReadyEvent>("model-ready-event"),
	modelsImportedEvent: makeEvent<ModelsImportedEvent>("models-imported-event"),
	runtimeDownloadFailedEvent: makeEvent<RuntimeDownloadFailedEvent>("runtime-download-failed-event"),
	runtimeDownloadProgressEvent: makeEvent<RuntimeDownloadProgressEvent>("runtime-download-progress-event"),
	runtimeReadyEvent: makeEvent<RuntimeReadyEvent>("runtime-ready-event"),
};

/* Types */
/**  灯箱角标数据：原图大小 + 来源文件夹状态（缩略图/原图标识，裁决 9） */
export type AssetDetail = {
	size_bytes: number | null,
	mime: string | null,
	folder_id: number,
	folder_label: string | null,
	folder_path: string,
	/**  online | offline | missing */
	folder_status: string,
};

export type AssetSummary = {
	/**  IPC 契约用 i32/f64（specta 禁 i64 导出；内部仍是 i64，量级远不触及边界） */
	asset_id: number,
	thumb_path: string | null,
	width: number | null,
	height: number | null,
	taken_at: number | null,
	/**  语义索引是否已建立（全部 active 索引均有向量；false=网格显示建索引呼吸点） */
	indexed: boolean,
};

/**  当前数据布局快照（设置对话框数据区） */
export type DataInfo = {
	/**  env | portable | rooted | classic */
	mode: string,
	/**  数据随应用目录携带（口袋式，含 env/rooted 指定的数据根） */
	portable: boolean,
	db_path: string,
	thumbs_dir: string,
	models_dir: string,
	logs_dir: string,
	/**  「打开数据文件夹」的目标目录 */
	data_folder: string,
	config_path: string,
	/**  是否允许在设置里更改位置（env 模式禁用） */
	can_change: boolean,
};

export type DeleteReport = {
	deleted: number,
	missing: number,
};

/**  向量化进度（每张写完发一次）：进度卡按工作区分组逐张推进 */
export type EmbedProgressEvent = {
	/**  该索引全库已嵌入资产数（绝对值） */
	done: number,
	/**  该索引全库应嵌总数（done + 队列剩余，仅在线工作区；冷却中的恒败项不计） */
	total: number,
	/**  本次会话累计解码失败数（源文件不可读等；重启清零） */
	failed: number,
	/**  刚完成这张的归属工作区（-1 = 与本事件无关的内部更新） */
	folder_id: number,
	/**  刚完成这张的文件名（进度卡逐张滚动展示） */
	file_name: string,
};

export type EpOption = {
	kind: string,
	/**  检测层面可用（DirectML：Windows；CUDA：运行时就绪） */
	available: boolean,
	/**  检测到独立显卡且变体就绪时提示推荐 */
	recommended: boolean,
	hint: string,
};

export type FailedItem = {
	asset_id: number,
	path: string,
	error_code: string | null,
};

/**  单工作区的向量化进度（进度卡按工作区分组展示） */
export type FolderEmbedStatus = {
	folder_id: number,
	label: string | null,
	/**  online | offline | missing（非 online 的待嵌项不会推进，前端标注「源离线」） */
	status: string,
	/**  ready 资产总数（分母） */
	total: number,
	/**  已有向量的 ready 资产数（分子） */
	done: number,
};

/**  文件夹（工作区）快照 */
export type FolderInfo = {
	folder_id: number,
	path: string,
	label: string | null,
	/**  online | offline | missing */
	status: string,
	asset_count: number,
	/**  待建索引的 ready 资产数（>0 时侧栏显示「建索引中 N」，规格 0007 §1） */
	pending_index: number,
};

/**  来源文件夹状态变化（online/offline/missing）→ 侧栏状态点与灯箱状态条刷新 */
export type FolderStatusChangedEvent = {
	folder_id: number,
	/**  online | offline | missing */
	status: string,
};

export type ImportFinishedEvent = {
	job_id: number,
	failed_count: number,
};

export type ImportItemFailedEvent = {
	job_id: number,
	path: string,
	error_code: string,
};

export type ImportPausedEvent = {
	job_id: number,
};

export type ImportProgressEvent = {
	job_id: number,
	total: number,
	done: number,
	failed: number,
	eta_seconds: number | null,
};

export type ImportReport = {
	imported: number,
	skipped: number,
	mismatched: ModelFileIssue[],
};

export type ImportResumedEvent = {
	job_id: number,
};

/**  单套索引的占用 */
export type IndexUsage = {
	index_id: number,
	slug: string,
	display: string,
	/**  active | disabled */
	status: string,
	count: number,
	/**  近似占用 = count × dim × 4（f32） */
	approx_bytes: number | null,
};

export type InferenceInfo = {
	/**  用户选择（config） */
	current_ep: string,
	/**  本次会话实际装配所用后端（降级后为 cpu） */
	effective_ep: string,
	/**  非空 = 本次会话发生过降级（所选后端不可用），前端展示原因 */
	degraded_reason: string | null,
	/**
	 *  非空 = 推理运行时整体不可用（变体缺失/清单损坏）：语义搜索与建索引停用，
	 *  其余功能照常；前端以此区分「降级但可用」与「语义功能停用」
	 */
	runtime_missing: string | null,
	options: EpOption[],
	/**  所选变体的运行时是否就绪（CUDA 下载/导入完成） */
	runtime_ready: boolean,
	/**  检测到独立显卡（NVIDIA/AMD 独显特征名，仅文案提示不作开关） */
	gpu_detected: boolean,
};

export type ModelDownloadProgressEvent = {
	file: string,
	received: number,
	total: number,
};

export type ModelFileIssue = {
	name: string,
	reason: string,
};

export type ModelReadyEvent = Record<string, never>;

export type ModelStatus = {
	ready: boolean,
	loaded: boolean,
	files_missing: string[],
};

/**  模型本地导入完成且装配成功 */
export type ModelsImportedEvent = Record<string, never>;

/**
 *  运行时包下载/安装失败（终态）：前端据此清除「下载中」并展示原因，
 *  否则进度事件之后再无任何信号，下载卡永久停留
 */
export type RuntimeDownloadFailedEvent = {
	error: string,
};

/**  运行时包下载进度（spec 0008 §3.3；复用模型下载进度模式） */
export type RuntimeDownloadProgressEvent = {
	received: number,
	total: number,
};

/**  运行时包就绪（下载/导入完成并通过校验） */
export type RuntimeReadyEvent = Record<string, never>;

/**  检索过滤器（日期区间 / 类型） */
export type SearchFilters = {
	taken_from: number | null,
	taken_to: number | null,
	kind: string | null,
	/**  搜索范围（v8 裁定：跟随侧栏所选工作区；None=全部） */
	folder_id: number | null,
};

export type SearchHit = {
	summary: AssetSummary,
	/**  RRF 归一分（0~1），越大越相关 */
	score: number | null,
	/**
	 *  语义相似度（余弦 0~1，两侧向量已 L2 归一化；纯文件名命中 = null）。
	 *  展示用，不参与排序；无阈值截断（2026-09-11 所有者裁定：先显示不设阈值）
	 */
	similarity: number | null,
	/**  命中来源：both / semantic / text（排序可解释，白皮书 §4.6） */
	matched: string,
	/**  结果元数据（UI 对齐 v6：文件名 / 大小 / 所属工作区） */
	file_name: string,
	size_bytes: number | null,
	folder_id: number,
	folder_label: string,
};

export type SearchPage = {
	items: SearchHit[],
	model_ready: boolean,
	pending_indexing: number,
	available_years: string[],
};

/**  存储占用分析（裁决 25：只展示，不做清理） */
export type StorageUsage = {
	db_bytes: number | null,
	wal_bytes: number | null,
	thumbs_bytes: number | null,
	models_bytes: number | null,
	assets_count: number,
	embedded_count: number,
	/**  各索引分项（裁定 25：占用分析到每一套索引） */
	per_index: IndexUsage[],
};

export type TimelinePage = {
	groups: YearGroup[],
	next_cursor: string | null,
};

export type YearGroup = {
	year: number,
	items: AssetSummary[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

