// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  示例命令：P0 用于验证 specta 契约链路（生成 → 引用 → CI 一致性检查） */
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	/**  启动导入：选择文件夹 → 引擎后台跑（重试 = 对同一文件夹再导一次，哈希幂等） */
	importFolder: (folder: string) => typedError<number, string>(__TAURI_INVOKE("import_folder", { folder })),
	pauseImport: () => __TAURI_INVOKE<void>("pause_import"),
	resumeImport: () => __TAURI_INVOKE<void>("resume_import"),
	/**  停止当前导入（确认后）；已处理部分保留，续传 = 重新导入同一文件夹 */
	stopImport: () => __TAURI_INVOKE<void>("stop_import"),
	/**  当前任务快照（前端轮询兜底，事件丢失时恢复用） */
	importSnapshot: () => typedError<ImportProgressEvent, string>(__TAURI_INVOKE("import_snapshot")),
	/**  时间轴分页查询：按拍摄时间降序，前端按年分组展示 */
	listTimeline: (cursor: string | null, pageSize: number | null) => typedError<TimelinePage, string>(__TAURI_INVOKE("list_timeline", { cursor, pageSize })),
	/**  原图绝对路径（asset protocol 读取；scope 在导入时放行） */
	getAssetImage: (assetId: number) => typedError<string, string>(__TAURI_INVOKE("get_asset_image", { assetId })),
	/**  批量删除记录与缩略图（永不触碰原文件） */
	deleteAssets: (assetIds: number[]) => typedError<DeleteReport, string>(__TAURI_INVOKE("delete_assets", { assetIds })),
	/**  失败清单 */
	listFailedItems: () => typedError<FailedItem[], string>(__TAURI_INVOKE("list_failed_items")),
	modelStatus: () => __TAURI_INVOKE<ModelStatus>("model_status"),
	/**  下载模型资产（后台线程；进度经事件上报，完成后加载并广播就绪） */
	downloadModels: () => typedError<null, string>(__TAURI_INVOKE("download_models")),
	/**  中文语义搜索（规格 0003）：文本编码 → KNN → join assets */
	searchAssets: (query: string, topK: number | null) => typedError<SearchPage, string>(__TAURI_INVOKE("search_assets", { query, topK })),
	/**  重建全部向量索引（模型变更/量化策略变更时）；worker 轮询发现空队列后全量重嵌 */
	reindexAll: () => typedError<number, string>(__TAURI_INVOKE("reindex_all")),
};

/** Events */
export const events = {
	embedProgressEvent: makeEvent<EmbedProgressEvent>("embed-progress-event"),
	importFinishedEvent: makeEvent<ImportFinishedEvent>("import-finished-event"),
	importItemFailedEvent: makeEvent<ImportItemFailedEvent>("import-item-failed-event"),
	importPausedEvent: makeEvent<ImportPausedEvent>("import-paused-event"),
	importProgressEvent: makeEvent<ImportProgressEvent>("import-progress-event"),
	importResumedEvent: makeEvent<ImportResumedEvent>("import-resumed-event"),
	modelDownloadProgressEvent: makeEvent<ModelDownloadProgressEvent>("model-download-progress-event"),
	modelReadyEvent: makeEvent<ModelReadyEvent>("model-ready-event"),
};

/* Types */
export type AssetSummary = {
	/**  IPC 契约用 i32/f64（specta 禁 i64 导出；内部仍是 i64，量级远不触及边界） */
	asset_id: number,
	thumb_path: string | null,
	width: number | null,
	height: number | null,
	taken_at: number | null,
};

export type DeleteReport = {
	deleted: number,
	missing: number,
};

export type EmbedProgressEvent = {
	done: number,
	total: number,
};

export type FailedItem = {
	asset_id: number,
	path: string,
	error_code: string | null,
};

export type ImportFinishedEvent = {
	job_id: number,
	failed_count: number,
};

export type ImportItemFailedEvent = {
	job_id: number,
	path: string,
	error_code: string,
};

export type ImportPausedEvent = {
	job_id: number,
};

export type ImportProgressEvent = {
	job_id: number,
	total: number,
	done: number,
	failed: number,
	eta_seconds: number | null,
};

export type ImportResumedEvent = {
	job_id: number,
};

export type ModelDownloadProgressEvent = {
	file: string,
	received: number,
	total: number,
};

export type ModelReadyEvent = Record<string, never>;

export type ModelStatus = {
	ready: boolean,
	loaded: boolean,
	files_missing: string[],
};

export type SearchHit = {
	summary: AssetSummary,
	/**  归一相似度（1 - L2²/4），越大越相关 */
	score: number | null,
};

export type SearchPage = {
	items: SearchHit[],
	model_ready: boolean,
	pending_indexing: number,
};

export type TimelinePage = {
	groups: YearGroup[],
	next_cursor: string | null,
};

export type YearGroup = {
	year: number,
	items: AssetSummary[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

