// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  示例命令：P0 用于验证 specta 契约链路（生成 → 引用 → CI 一致性检查） */
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
};

